
/**
 * Jest Configuration for Smart Tourist Safety System
 * Generated by setup_test_environment.js
 */

module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)'
  ],
  setupFilesAfterEnv: [
    '@testing-library/jest-native/extend-expect'
  ],
  collectCoverageFrom: [
    '**/mobile/src/**/*.{js,jsx,ts,tsx}',
    '!**/node_modules/**',
    '!**/web-build/**'
  ],
  coverageReporters: ['json', 'lcov', 'text', 'clover', 'html'],
  testMatch: [
    '**/__tests__/**/*.{js,jsx,ts,tsx}',
    '**/?(*.)+(spec|test).{js,jsx,ts,tsx}',
    '**/tests/**/*.{js,jsx,ts,tsx}'
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node']
};
