/**
 * Test Environment Setup Script
 * 
 * This script sets up the test environment for the user registration flow tests.
 * It creates necessary directories, installs dependencies, and configures the test environment.
 * 
 * Usage: node setup_test_environment.js
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Configuration
const config = {
  reportsDir: path.join(__dirname, 'reports'),
  screenshotsDir: path.join(__dirname, 'screenshots'),
  mockDataDir: path.join(__dirname, 'mock_data'),
  dependencies: [
    '@testing-library/react-native',
    '@testing-library/jest-native',
    'jest',
    'jest-expo'
  ]
};

console.log('\n======================================');
console.log('Setting up Test Environment');
console.log('======================================\n');

// Create necessary directories
function createDirectories() {
  console.log('Creating necessary directories...');
  
  const directories = [
    config.reportsDir,
    config.screenshotsDir,
    config.mockDataDir
  ];
  
  directories.forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(`Created directory: ${dir}`);
    } else {
      console.log(`Directory already exists: ${dir}`);
    }
  });
  
  console.log('Directories setup complete.\n');
}

// Install test dependencies
function installDependencies() {
  console.log('Checking and installing test dependencies...');
  
  try {
    // Check if package.json exists in the project root
    const projectRoot = path.join(__dirname, '..');
    const packageJsonPath = path.join(projectRoot, 'package.json');
    
    if (!fs.existsSync(packageJsonPath)) {
      console.error('Error: package.json not found in project root.');
      console.error('Please run this script from the project directory that contains package.json.');
      process.exit(1);
    }
    
    // Read package.json to check existing dependencies
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    const existingDeps = { ...packageJson.dependencies, ...packageJson.devDependencies };
    
    // Filter out dependencies that are already installed
    const depsToInstall = config.dependencies.filter(dep => !existingDeps[dep]);
    
    if (depsToInstall.length === 0) {
      console.log('All required dependencies are already installed.');
    } else {
      console.log(`Installing missing dependencies: ${depsToInstall.join(', ')}`);
      execSync(`npm install --save-dev ${depsToInstall.join(' ')}`, { stdio: 'inherit' });
      console.log('Dependencies installed successfully.');
    }
  } catch (error) {
    console.error('Error installing dependencies:');
    console.error(error.message);
    process.exit(1);
  }
  
  console.log('Dependencies setup complete.\n');
}

// Configure Jest
function configureJest() {
  console.log('Configuring Jest...');
  
  try {
    const projectRoot = path.join(__dirname, '..');
    const jestConfigPath = path.join(projectRoot, 'jest.config.js');
    
    // Check if Jest config already exists
    if (fs.existsSync(jestConfigPath)) {
      console.log('Jest configuration already exists. Skipping creation.');
      return;
    }
    
    // Create basic Jest configuration
    const jestConfig = `
/**
 * Jest Configuration for Smart Tourist Safety System
 * Generated by setup_test_environment.js
 */

module.exports = {
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)'
  ],
  setupFilesAfterEnv: [
    '@testing-library/jest-native/extend-expect'
  ],
  collectCoverageFrom: [
    '**/mobile/src/**/*.{js,jsx,ts,tsx}',
    '!**/node_modules/**',
    '!**/web-build/**'
  ],
  coverageReporters: ['json', 'lcov', 'text', 'clover', 'html'],
  testMatch: [
    '**/__tests__/**/*.{js,jsx,ts,tsx}',
    '**/?(*.)+(spec|test).{js,jsx,ts,tsx}',
    '**/tests/**/*.{js,jsx,ts,tsx}'
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node']
};
`;
    
    fs.writeFileSync(jestConfigPath, jestConfig);
    console.log(`Created Jest configuration at: ${jestConfigPath}`);
  } catch (error) {
    console.error('Error configuring Jest:');
    console.error(error.message);
    process.exit(1);
  }
  
  console.log('Jest configuration complete.\n');
}

// Create mock data for tests
function createMockData() {
  console.log('Setting up mock data...');
  
  try {
    // Copy test data to mock_data directory
    const testDataPath = path.join(__dirname, 'user_registration_test_data.json');
    const mockDataPath = path.join(config.mockDataDir, 'user_registration_test_data.json');
    
    if (fs.existsSync(testDataPath)) {
      fs.copyFileSync(testDataPath, mockDataPath);
      console.log(`Copied test data to: ${mockDataPath}`);
    } else {
      console.warn(`Warning: Test data file not found at: ${testDataPath}`);
    }
    
    // Create additional mock data if needed
    const mockAuthServicePath = path.join(config.mockDataDir, 'mock_auth_service.js');
    const mockAuthService = `
/**
 * Mock AuthService for testing
 */

const mockAuthService = {
  login: jest.fn().mockResolvedValue({
    access_token: 'mock_token',
    refresh_token: 'mock_refresh_token',
    tourist: {
      id: 'tourist-1234',
      name: 'Test User',
      phone: '9876543210',
      safety_score: 100,
      entry_point: 'Mobile App Registration',
      is_active: true
    }
  }),
  register: jest.fn().mockResolvedValue({
    access_token: 'mock_token',
    refresh_token: 'mock_refresh_token',
    tourist: {
      id: 'tourist-1234',
      name: 'Test User',
      phone: '9876543210',
      safety_score: 100,
      entry_point: 'Mobile App Registration',
      is_active: true
    },
    digital_id: {
      id: 'TSN-1234567890',
      blockchain_hash: '0x1234567890abcdef',
      issued_date: new Date().toISOString(),
      expiry_date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString()
    }
  }),
  verifyDigitalId: jest.fn().mockResolvedValue(true)
};

module.exports = mockAuthService;
`;
    
    fs.writeFileSync(mockAuthServicePath, mockAuthService);
    console.log(`Created mock AuthService at: ${mockAuthServicePath}`);
  } catch (error) {
    console.error('Error creating mock data:');
    console.error(error.message);
    process.exit(1);
  }
  
  console.log('Mock data setup complete.\n');
}

// Add npm scripts for testing
function addNpmScripts() {
  console.log('Adding npm scripts for testing...');
  
  try {
    const projectRoot = path.join(__dirname, '..');
    const packageJsonPath = path.join(projectRoot, 'package.json');
    
    if (!fs.existsSync(packageJsonPath)) {
      console.error('Error: package.json not found in project root.');
      return;
    }
    
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    
    // Add or update test scripts
    packageJson.scripts = packageJson.scripts || {};
    
    const scriptsToAdd = {
      'test:registration': 'node tests/run_registration_tests.js',
      'test:setup': 'node tests/setup_test_environment.js',
      'test:all': 'jest --coverage'
    };
    
    let scriptsAdded = false;
    for (const [key, value] of Object.entries(scriptsToAdd)) {
      if (!packageJson.scripts[key]) {
        packageJson.scripts[key] = value;
        scriptsAdded = true;
      }
    }
    
    if (scriptsAdded) {
      fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2));
      console.log('Added npm scripts for testing.');
    } else {
      console.log('Test scripts already exist in package.json.');
    }
  } catch (error) {
    console.error('Error adding npm scripts:');
    console.error(error.message);
  }
  
  console.log('npm scripts setup complete.\n');
}

// Main function to run all setup steps
function main() {
  try {
    createDirectories();
    installDependencies();
    configureJest();
    createMockData();
    addNpmScripts();
    
    console.log('\n======================================');
    console.log('Test Environment Setup Complete');
    console.log('======================================');
    console.log('\nYou can now run the tests using:');
    console.log('npm run test:registration');
    console.log('\nOr run all tests with:');
    console.log('npm run test:all');
    console.log('\n======================================\n');
  } catch (error) {
    console.error('\nError setting up test environment:');
    console.error(error.message);
    process.exit(1);
  }
}

// Run the setup
main();